"""Generate product artwork from assets/branding/hydra.png (requires Pillow)."""

from base64 import b64encode
from io import BytesIO
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont, ImageOps, ImageSequence


ROOT = Path(__file__).resolve().parents[1]


def write(relative: str, content: str) -> None:
    target = ROOT / relative
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8", newline="\n")


def main() -> None:
    original = Image.open(ROOT / "assets/branding/hydra.png").convert("RGBA")
    artwork = original.crop(original.getbbox())
    logo = Image.new("RGBA", (256, 256))
    resized = ImageOps.contain(artwork, (240, 240), Image.Resampling.LANCZOS)
    logo.alpha_composite(resized, ((256 - resized.width) // 2, (256 - resized.height) // 2))
    png = BytesIO()
    logo.save(png, format="PNG", optimize=True)
    uri = "data:image/png;base64," + b64encode(png.getvalue()).decode("ascii")
    write("packages/client/ui-primitives/src/hydra-logo-data.ts",
          "/** Generated by scripts/gen-brand-assets.py from the supplied Hydra artwork. */\n"
          "/** Embedded logo shared by bundled client renderers. */\n"
          f"export const hydraLogoData = '{uri}'\n")
    animation = Image.open(ROOT / "assets/branding/hydra-hover.gif")
    frames = [frame.convert("RGBA") for frame in ImageSequence.Iterator(animation)]
    durations = [frame.info["duration"] for frame in ImageSequence.Iterator(animation)]
    bounds = [frame.getbbox() for frame in frames]
    crop = (min(box[0] for box in bounds), min(box[1] for box in bounds),
            max(box[2] for box in bounds), max(box[3] for box in bounds))
    scaled = []
    for frame in frames:
        canvas = Image.new("RGBA", (128, 128))
        resized = ImageOps.contain(frame.crop(crop), (120, 120), Image.Resampling.LANCZOS)
        canvas.alpha_composite(resized, ((128 - resized.width) // 2, (128 - resized.height) // 2))
        scaled.append(canvas)
    webp = BytesIO()
    scaled[0].save(webp, format="WEBP", save_all=True, append_images=scaled[1:],
                   duration=durations, loop=0, lossless=True, method=6)
    (ROOT / "website/public/hydra-hover.webp").write_bytes(webp.getvalue())
    hover_uri = "data:image/webp;base64," + b64encode(webp.getvalue()).decode("ascii")
    write("packages/client/ui-primitives/src/hydra-hover-data.ts",
          "/** Generated by scripts/gen-brand-assets.py from the supplied animated Hydra artwork. */\n"
          "/** Embedded hover animation shared by bundled client renderers. */\n"
          f"export const hydraHoverData = '{hover_uri}'\n")
    svg = (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="none">\n'
           f'  <image width="256" height="256" href="{uri}"/>\n</svg>\n')
    for destination in ["apps/web/public/favicon.svg", "website/public/favicon.svg"]:
        write(destination, svg)
    write("website/public/wordmark.svg",
          '<svg xmlns="http://www.w3.org/2000/svg" width="182" height="24" viewBox="0 0 182 24">\n'
          f'  <image class="hydra-still" width="24" height="24" href="{uri}"/>\n'
          '  <image class="hydra-motion" display="none" width="24" height="24" href="hydra-hover.webp"/>\n'
          '  <text x="30" y="17" fill="currentColor" font-family="system-ui, sans-serif" '
          'font-size="17" font-weight="600">Hydra harness</text>\n</svg>\n')
    for destination in ["apps/desktop/assets/hydra.png", "packages/browser/browser-electron/electron-app/hydra.png"]:
        target = ROOT / destination
        target.parent.mkdir(parents=True, exist_ok=True)
        logo.save(target, optimize=True)
    logo.save(ROOT / "apps/desktop/assets/hydra.ico", sizes=[(16, 16), (32, 32), (48, 48), (64, 64), (128, 128), (256, 256)])
    badge = Image.new("RGBA", (1080, 168), "#101a35")
    badge.alpha_composite(ImageOps.contain(artwork, (144, 144), Image.Resampling.LANCZOS), (12, 12))
    draw = ImageDraw.Draw(badge)
    draw.text((182, 23), "powered by", font=ImageFont.load_default(size=36), fill="#c5d9ec")
    draw.text((182, 68), "Hydra harness", font=ImageFont.load_default(size=64), fill="white")
    badge.save(ROOT / "packages/skill/skill-badge/assets/hydra-badge.png", optimize=True)
    print("Generated Hydra client logo, favicons, desktop icons, wordmark and badge.")


if __name__ == "__main__":
    main()
