/** Generated by scripts/gen-brand-assets.py from the supplied animated Hydra artwork. */
import hydraHoverUrl from './hydra-hover.webp'
/** WebP URL shared by bundled client renderers. */
export const hydraHoverData = hydraHoverUrl
