/** Generated by scripts/gen-brand-assets.py from the supplied Hydra artwork. */
import hydraLogoUrl from './hydra-logo.png'
/** PNG URL shared by bundled client renderers. */
export const hydraLogoData = hydraLogoUrl
